version: '3'

services:
  demo-postgres-compose:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "Demo2021!"
    ports:
      - "15432:5432"
    volumes:
      - /Users/Paulo.maestro/source/repos/Demo.Clean.Arch/PostgreSQL:/var/lib/postgresql/data 
    networks:
      - postgres-compose-network
      
  teste-pgadmin-compose:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "Demo"
      PGADMIN_DEFAULT_PASSWORD: "Demo2021!"
    ports:
      - "8080:80"
    depends_on:
      - demo-postgres-compose
    networks:
      - postgres-compose-network

networks: 
  postgres-compose-network:
    driver: bridge